async function calculate(number) {
    var data = [];

    var resultRows = d3.selectAll("tr");

    for (var i = 1; i <= Math.min(number, resultRows.length); i++) {
        let ticker = (resultRows[i].attr('id').split('_'))[-1];
    }
    
    for (var i = groupStart; i <= groupEnd; i++) {    
        var symbols = data[i - 1];
        let timeoutEnd = (new Date()).getTime() + 12;
        do {} while ((new Date()).getTime() < timeoutEnd)
        let url = `https://cloud.iexapis.com/stable/stock/market/batch?symbols=${symbols}&types=chart,stats&range=5y&chartCloseOnly=true&token=${apiKey}`;
        const done = await axios.get(url)
            .then(response => {
                let keys = Object.keys(response.data);
                keys.forEach(key => {
                    let chartData = response.data[key].chart;
                    if (chartData.length > 1258) {
                        chartData.forEach(day => {
                            resultElement.append("span")
                                .html(`<br>${key}~${day.date}~${day.close}~${day.volume}~${response.data[key].stats.marketcap}`);
                        });
                    }
                });
            })
            .catch(error => {
                console.log(error);
            });
    }
}

function drawTable(data) {
    console.log(data);
    var resultElement = d3.select("#result");
    resultElement.html("");
    var resultTable = resultElement.append("table").attr("id", "resultTable");
    var resultLabels = resultTable.append("tr").attr("id", "resultLabels");
    resultLabels.append("th").attr("id", "resultLabelTicker").html("Ticker");
    resultLabels.append("th").attr("id", "resultLabel30Day").html("30 Day Change");
    resultLabels.append("th").attr("id", "resultLabel5Day").html("5 Day Change");
    resultLabels.append("th").attr("id", "resultLabelMarketCap").html("Market Cap");

    data.forEach(x => {
        let resultRow = resultTable.append("tr").attr("id", `resultDataRow_${x.ticker}`)
        resultTable.append("td")
            .attr("id", `resultDataTicker_${x.ticker}`)
            .html(`<a href="https://finance.yahoo.com/quote/${x.ticker}/history" target="_blank">${x.ticker}</a>`);
        resultTable.append("td")
            .attr("id", `resultData30Day_${x.ticker}`)
            .html(Intl.NumberFormat('en-US', {style: 'percent', minimumFractionDigits: 2, maximumFractionDigits: 2}).format(x.day30));
        resultTable.append("td")
            .attr("id", `resultData5Day_${x.ticker}`)
            .html(Intl.NumberFormat('en-US', {style: 'percent', minimumFractionDigits: 2, maximumFractionDigits: 2}).format(x.day5));
        resultTable.append("td")
            .attr("id", `resultDataMarketCap_${x.ticker}`)
            .html(`${Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(x.marketcap)}`);
    });
}

(async () => {
    var data = [
        "AAPL,MSFT",
        "SEEL,TLRY,CHRS,ARDX,AXSM,AKTS,AVEO,RGNX,ITRM,SQL,TUEM,LCID,NCMI,ACRS,VIVE,DXCM,VBLT,ACAI,NLTX,ARDS,WWR,PEGA,WOLF,JNCE,MTCR,RIGL,EDSA,CRWD,APEI,BLIN,SKYT,NKTR,GNPX,CRDL,ACB,RARE,IGMS,RVPH,SPWR,HSTO,LGO,VFF,DAWN,IMRX,LLNW,NSPR,CGRN,ONTX,PLTK,SUNW,CYRN,CTMX,MRUS,TIL,CARA,VERX,RDUS,ORTX,AKRO,AFMD,OCGN,ATXS,MRTX,VERV,DRUG,DRMA,TIRX,CDMO,CELU,TTD,MEDS,MYSZ,CRKN,AVXL,SG,HCWB,NUZE,STRO,CMBM,CKPT,OLB,BLI,TNGX,MNTV,SABR,LYLT,MBRX,SRNE,SLNH,LPCN,CJJD,SINT,JAMF,LPTX,CBIO,RXDX,VYNT,SILK,CRTX,ALRN",
        "ACAD,ENVX,PRLD,NTLA,BMRA,GNUS,NVEI,ABCL,GBIO,STRC,CGEN,TGTX,AUVI,ALGS,DATS,REE,IDXX,BFRI,CLRB,LPSN,RAIL,LTCH,LXRX,SWAV,SATL,JAN,ATIF,DOMO,SLGC,ALGN,HYPR,XCUR,FNGR,ATAI,CGNX,RVMD,RRGB,FORG,VORB,GMDA,ETNB,OCUP,AXDX,TEAM,GBS,NAOV,ALEC,EVER,PRTK,AIP,AEZS,PRDS,ADN,AVID,CNTX,HSDT,SANA,GLUE,MRSN,AGEN,KRON,BEEM,CWBR,PIII,BNFT,CABA,INMD,VRM,GRPN,HTOO,BSY,AMSC,HNST,RKDA,ACET,IMV,DH,ASMB,PLBY,INDP,SMLR,XFOR,ONCT,ARWR,ANGH,NUVL,SELB,CEMI,APLS,ARTW,DCGO,DTST,LVO,CING,TSRI,CTSO,VERA,AREC,AVCO,ONCS",
        "AERC,IZEA,HBIO,PLXP,LAZR,HEPA,SNDL,CYBR,SXTC,SGMO,PETQ,OYST,IMTX,NUWE,CODX,CGEM,UGRO,SPPI,UK,SPLK,VISL,AGTC,SLS,AQMS,RKLB,RETO,VVPR,STNE,DSGN,TALK,AXNX,PDSB,ONEM,SAVA,GANX,ENVB,PHUN,KPLT,DRTT,CDRO,LQDT,MTTR,VRPX,OLMA,OPNT,ATEC,DERM,SFT,CDLX,TOIIW,VLTA,CLBS,NXTC,CERE,HAPP,BIGC,AEYE,VLDR,BEAM,SRAD,ETSY,PRCH,XP,AMTI,LUCD,COUP,VERU,DOCU,GGE,ARAV,VCYT,ANGN,BLCM,ZY,HSKA,NKLA,SOFO,PTE,KTOS,NEXI,ZS,TARS,IMPP,AVRO,GRAY,DARE,KALA,ACMR,SBET,TALS,NVTS,SANG,ANDE,TOMZ,OTRK,PIK,GEVO,XOMA,SGLY,SYBX",
        "CRMD,POLA,GROM,STAF,ILMN,LOOP,FLYW,AHPI,TWST,FLNC,MQ,CSCW,QUBT,SERA,TANH,ATRC,WIX,AIRS,ASTR,WBD,ARAY,EFOI,VSTM,MELI,WVE,EGHT,CLLS,NDRA,VBIV,HOFV,IMGN,EDUC,LLL,AEHL,EKSO,ROOT,CLSN,CPOP,PRQR,REVB,KROS,TACT,IDRA,SPRB,HCP,ACIU,GBT,MARK,PMVP,AYRO,LMNL,CRIS,CCNC,MAPS,GSHD,TOPS,DUOL,ATRA,NURO,NARI,ATHX,FSII,MIGI,MITI,APDN,CRSR,KNBE,NEGG,FATE,YMAB,KPTI,BIMI,TFFP,LILM,NXTP,SWTX,ARRY,MDIA,AZ,SMFR,SCPS,RNA,SRGA,TRUP,LUNG,CRTD,AQB,CDNA,AXON,VRNS,MNTS,WKHS,ME,ALR,GTHX,ISEE,SANW,MKTW,PLL,BYND",
        "INBX,MESA,WPRT,NOVA,BITF,TELL,LOGC,CRDO,GOVX,CLSD,NN,GLG,LGMK,HILS,BTAI,RUN,ALIM,CYRX,APWC,PHAS,PETZ,ROKU,CURI,SIEN,HEAR,TCMD,MYMD,APPS,EBON,LEDS,SMTI,NHWK,RPID,MDWT,TSVT,TTNP,BTRS,MDB,SABS,PYPL,WMG,TAST,UNCY,QUMU,CSIQ,XXII,MOXC,PTRA,NISN,RELY,TWOU,ORIC,VXRT,FAMI,TNDM,PHCF,INSG,RELI,APM,EYEN,SDGR,FLGC,SMFL,BNGO,FORA,BLDE,TTCF,TMCI,ALT,SDC,ALLR,HGEN,BLZE,HCTI,ENLV,SEV,FARO,BLNK,MOVE,EGLX,LTRPB,FIXX,OMIC,SOPA,AVTE,FDMT,VYNE,INSP,SLHG,CLOV,AGFY,CSTL,WISA,KPRX,PRVA,DLO,NTRA,WAVD,NTEC,CLNN",
        "RETA,UROY,LFST,BMBL,WKSP,LPRO,SSIC,AAOI,OPEN,APPH,WISH,ISPO,CLPT,CRBP,SUMO,ROIV,TERN,ADXS,PGEN,BAFN,EVOK,ATNX,AVAV,OKTA,SMSI,SKIN,MITK,PRFX,ADGI,HYZN,LPTH,LOTZ,PPSI,ONCR,QMCO,STRR,ADIL,GNLN,BFLY,HUSN,ZIP,BTCS,ELDN,BVS,ATLC,NMTR,TNXP,SEER,FPAY,SLNO,NGM,RCKT,KOSS,QTEK,ARVN,SLGG,PBYI,EVCM,DNLI,APEN,CUEN,VOXX,DTIL,CRVS,CYTH,BASE,AMED,HCICW,BOLT,OBLG,SGTX,EVLO,KALV,AMZN,FTRP,ACRX,JAGX,GTEC,PRVB,TTSH,MGTX,SIBN,AVGR,EVK,SOLO,SNTG,AMPG,PIRS,BSFC,IDXG,VRAY,TARA,PLRX,WING,ENTA,SONO,GTBP,EQ,SJ,VRCA",
        "IEA,APRE,ONCY,ZNTL,USAU,SPRC,GRTX,DWSN,FHTX,OPRX,MASS,BXRX,RPD,CSII,VIRT,ALLT,NUTX,RVNC,KURA,XBIT,XPON,HLVX,GRTS,YVR,RDFN,EAST,AADI,VS,VCEL,INO,DNAY,CREG,EDIT,ARTL,NVCR,PATH,ACLX,ADV,MBIO,CZR,VIRX,YTEN,ATER,CTXR,VYGR,MVST,MDGL,ACVA,MVIS,KRUS,STAB,FLL,ELMS,PCSA,PACB,IDEX,MORF,CMPR,PNT,STOK,MILE,CPSH,FROG,ERAS,ASTS,GLBE,CGIX,WAFU,CDXC,UBX,ADMP,HRTX,IKT,BHTG,BRTX,RPAY,REED,XELA,BAND,DCBO,TRKA,CRSP,SOFI,PYXS,DKNG,GRPH,NRIX,PSTI,XELB,BYSI,VRDN,CXDO,CNSP,VRAR,AGIO,CMAX,TMC,KAVL,EVGO,INSM",
        "VQS,HRMY,EZGO,GRAB,KOD,NMRD,CLVR,ZTEK,STIM,DTSS,SPT,IMTE,ELYS,LIND,ASRT,BLDP,SHYF,DYN,BNTC,INAB,RMBL,SONN,APYX,SCKT,PERI,FTFT,PRPL,CYTR,XERS,EJH,TW,MRIN,VGFC,DSP,DMRC,TPIC,BDTX,CADL,IPSC,NATR,KNSA,FRPT,NOVN,INVO,XBIO,ALVR,OCUL,SES,HOOD,CLNE,CRCT,STSA,PHAT,HTGM,NRBO,GOCO,WTRH,AGLE,REKR,BCEL,NEPT,TENB,RCRT,FTCI,BIRD,CVT,CORT,GAN,APTO,ONVO,USIO,APPF,GHSI,RSLS,VMAR,NEO,CTKB,SBNY,KRMD,SEDG,AMTX,SFM,SCYX,BIVI,KRYS,PODD,XSPA,LWAY,MOGO,ADMA,SGBX,UPWK,TCX,FLWS,IOVA,CGC,MTCH,PRTA,SNPX,SURF",
        "CARG,WVVI,NVCN,SCTL,FMTX,ATHA,FCEL,CNTY,XM,TSHA,Z,ACER,DOGZ,EXAS,JUPWW,DDOG,ABNB,SEAC,CIDM,PTCT,TCON,INFN,EBET,AUR,CRDF,KBNT,BCDA,MDXG,MAXN,FTHM,TBBK,MDJH,CUE,GTYHW,ILPT,BWEN,GLYC,DVAX,GMVD,EPZM,BTCY,VEV,FEAM,TLS,TRVI,ENSC,IONM,OEG,APP,NLSP,TXG,NRDS,BLBX,ANEB,OPTN,TENX,KRTX,OSTK,SPCB,BCRX,FBIO,PPTA,RNXT,IKNA,AMLX,IMGO,ACON,VVOS,MTRX,NBEV,PSNL,MCRB,IBRX,BRP,AMEH,CROX,TASK,RLMD,RCAT,KOPN,ORMP,ENPH,RSVR,DISH,NERV,RXRX,FGF,SFIX,TREE,EVGN,JANX,FSLY,OTMO,MRNS,VRME,ALHC,FUSN,SNGX,COLL,IPA",
        "LCFY,LEE,BL,QSI,CBAY,ADPT,LEXX,GGR,AIHS,GOEV,ZG,VLNS,RCON,GSMG,SRAX,VUZI,YMTX,WRAP,INGN,SCHN,BRLT,NRXP,FTAI,LFMD,AOSL,EEIQ,AUGX,QTRX,SNSE,SNPO,LAB,LTRX,RAIN,BTOG,SDH,HUT,GLSI,VBNK,PROF,LAND,APCX,NBSE,LYL,SOND,SEAT,ZENV,LGND,CRYP,LWLG,LYFT,PARA,PLSE,THRX,EYE,TDUP,EYPT,GLTO,IAS,SRPT,GREE,ABUS,MNKD,DENN,BLFS,DHC,RUBY,GTLB,ALPP,NBRV,ZI,COCP,MLTX,RIDE,OPTT,SPNE,TWKS,EVBG,CYCN,NVAX,QLGN,ZIOP,BWV,MGNI,REPL,ZYNE,GP,PYCR,IREN,LIVN,ADCT,RADA,DRCT,SSKN,TVTX,SLDP,VIRI,CASI,TTWO,POSH,DFFN",
        "DUOT,VMEO,SEED,MTBC,GTIM,UG,AERI,ATY,BRAG,RAVE,SESN,BRZE,EXPE,ALDX,FARM,LILAK,CLRO,KTTA,ALLK,TSLA,INTU,OSUR,INKT,INNV,BSQR,CUTR,CCXI,TYME,PWP,RIVN,GMBL,LITM,PARAA,DRTS,FSRD,HITI,STSS,ELOX,DPRO,QRTEA,BRCN,SMRT,CFMS,VCSA,THMO,VLON,HCAT,HOOK,ENOB,ISRG,FOLD,FFHL,RVSN,NRSN,SGHT,WW,UTME,AXLA,WEJO,SKIL,IINN,LTBR,OMEX,LHDX,SMED,SVC,PALT,ONDS,CPTN,SRRK,EQRX,TCDA,SNAX,NVVE,CRNX,BBCP,AYLA,NVDA,HTCR,NTRB,PGNY,HYMC,MSGM,GPRO,CEAD,DYNT,NVFY,LILA,HIVE,TCRX,DMTK,BHAT,MIND,CHNR,DIBS,SNCR,BGFV,PAAS,KIDS,NCLH",
        "CDXS,ANY,GRIL,AMBA,ALF,VITL,CETX,WDAY,AVDX,PLUG,FRSH,BIOC,RCM,ARCE,CTIB,FUV,ALTO,ORGO,ATXI,SSYS,LIDR,URGN,CELC,STAA,BBLG,GOSS,WRLD,GBNH,PANW,VIVK,INFI,ALXO,PALI,HAIN,KRNT,PTON,USWS,HYRE,ALNY,OFLX,TTEC,OGI,VERB,WEN,PASG,AUTO,SNBR,FSTX,AEMD,AKU,YELL,ADTX,LIQT,RAPT,NMTC,BWMX,GHRS,NTNX,RBOT,CCRN,BPTH,MBOT,HUMA,ACST,SSNT,UNIT,ZBRA,IMVT,OB,SGLB,CTIC,HTBX,ASPU,NPCE,BEAT,CENX,IESC,ARHS,LOVE,MRNA,SRZN,ARCT,CTLP,OSPN,AYTU,IFBD,CFRX,ASTC,CLSK,MTEK,MNMD,LMDX,CNET,BFI,JCSE,BTBT,REAL,ISO,ASTL,MCRI",
        "IRIX,AUUD,LABP,VERO,XRAY,OVID,EZFL,ZM,LTRPA,CNEY,NXPL,PFMT,CRNC,ATCX,LE,LUNA,UIHC,FEMY,FRHC,LYRA,DLPN,XAIR,ABMD,NXGL,SNDX,MGNX,VLCN,COSM,ATNF,JOUT,HZNP,DXLG,SWIM,BOSC,CNMD,PUBM,PAYO,VRSN,MACK,CDTX,WTER,PACW,VWE,STEP,ICUI,OLED,QLI,LQDA,FSLR,FYBR,SLNG,CTAC,PENN,ZD,CHCI,JYNT,AESE,PCOR,BIOL,CWST,WATT,TGEN,AIKI,TBLA,LGVN,DXYN,ULCC,SHLS,NDAQ,ALBO,SALM,IAC,ARQT,BPMC,TNYA,CGTX,QLYS,AMPL,KLXE,NAII,PTLO,CASH,QDEL,EPIX,HEXO,BTEK,ARBE,FIVE,BYRN,QRTEB,WINT,FINW,RDWR,INVA,SYRS,EMMA,SSP,CYCC,ICVX,LULU",
        "MNOV,VERI,RLAY,FFIV,COGT,DRRX,BGCP,SCWX,CVGW,CDEV,ABSI,SRDX,AAME,NWS,TPST,OMER,HARP,CRNT,AEHR,AREB,IOBT,EVLV,BBIO,GAME,ATOS,KMDA,HQI,BMEZ,TYRA,ABEO,FTNT,KRBP,FIVN,BRFH,SUPN,LBRDA,NAUT,EXFY,CNDT,MINM,APTX,GK,LMNR,BBBY,PCTY,GMGI,HQY,XMTR,HYFM,BOXL,NFLX,TELA,FNWB,DCTH,IMPL,ABOS,RWLK,JBLU,PRSO,FOCS,INTI,PZZA,LESL,TRVN,CNTG,IMNM,OCG,APLT,DGHI,MIST,AKUS,AMPH,CIFR,ESTA,HIHO,JZXN,MOTS,IPAR,BBI,ALLO,AMSWA,SVFD,CHTR,VSTA,IMUX,SND,NWSA,PSTV,LBRDK,BCAB,TECH,IDN,SNES,ROAD,BLBD,MDRX,FGEN,YGMZ,CFLT,CLDX",
        "TROW,SRCL,DTEA,GRWG,PI,MMAT,CCCC,WRPT,CLBT,CENN,SONM,JJSF,LOGI,AUPH,ISIG,AGMH,CERT,TOI,NVEE,KYMR,ANGO,VINP,ASYS,AMRK,NOTV,PEAR,VOR,EQOS,VRSK,FTEK,ETON,FOSL,LMFA,MRVI,CAMP,PEGY,BCLI,ALKT,ARVL,NEOG,RILY,REAX,MYNZ,TEUM,SOPH,FNCB,HSII,PAYS,KIRK,SNDA,CALA,MTC,ANSS,VKTX,ELBM,GILT,EXTR,MNPR,ITIC,LTRN,CPRX,AQST,VINC,GURE,NVIV,TTEK,TRUE,PRTH,APVO,HTZ,AUDC,WINN,TTGT,BOOM,SOHO,TUSK,NATI,KVHI,TSCO,OPGN,RDNT,AOUT,CONN,OM,AKBA,UTRS,VSAT,LRMR,LZ,CMTL,PCRX,QTNT,GWRS,TRHC,NNOX,FBRX,ELYM,NESR,VTGN,SSNC",
        "MARA,RGF,RNW,WTRE,ZEUS,OPK,LTRY,MDNA,BCOR,IFRX,AGRI,OLPX,IMMX,UEPS,RNAZ,LUMO,OTIC,WORX,SWKS,ARQQ,RANI,PRPH,AMOT,CHIR,MEDP,RDIB,ANGI,REFR,GBOX,RXT,DYAI,ALIT,SHCR,ICMB,EXPO,BRY,PNBK,SRCH,ENTR,BBGI,PWFL,CPIX,NRC,ACHV,WYNN,GIII,LGHLW,BTX,TGLS,SISI,MRAM,CLWT,ENTX,ICCM,ZIVO,ICLR,TPAY,LNW,AY,PTPI,FNCH,DCFC,SGEN,SLP,ADTH,SGRY,CME,LAKE,GGPIU,GDEN,SQFT,FTDR,RVLP,MNDO,XLO,EWTX,ARKO,CTSH,WHLM,STKL,PCT,NSSC,EQIX,ALOT,ANIP,DRIO,RPHM,IBKR,ALYA,ADVM,AKAM,RFIL,NBIX,PSTX,ZION,ZCMD,ACOR,NEPH,INZY,INTA",
        "CVCY,UPLD,FWBI,ENDP,PSHG,LOB,CYT,SAGE,FONR,WNW,CISO,IONS,AMCX,PBTS,CORZ,MIRM,CRXT,QNST,DCT,ASPS,CRBU,HELX,CAPR,KNDI,GOLD,VRTX,OLLI,CGO,SYNH,SNCE,MYGN,PBLA,CGNT,CSQ,CMCSA,VNDA,OFIX,COST,PULM,SPWH,BCYP,ATRI,VRTS,VEEE,EMKR,IPDN,OPI,AVPT,SNFCA,ORLY,STKS,LMB,TIGO,VIEW,POWW,FSV,RITA,XRTX,OTLK,IRDM,KSPN,GGPI,TRDA,MDWD,CLXT,ADES,FLUX,NMRK,STER,FOXF,SGML,RMTI,WKME,MPAA,SNPS,BLU,CDAK,AEY,GTX,WFRD,CCEL,RRR,GOGO,TIPT,FA,HAYN,TLIS,SDIG,GALT,CLPS,ADSE,WLDN,OMGA,IMCC,WWD,KERN,SURG,PCYO,RIOT,NEON",
        "CRVL,MHUA,RGLD,LNDC,GOOD,WTW,LVOX,XENE,CELZ,LIXT,MRKR,YAYO,ALTR,CODA,CTRN,LINC,FLGT,AMTD,HMST,CCOI,SIEB,VCNX,SIDU,REGN,PRPO,FWONK,TRIN,GDRX,HFFG,SPSC,FWONA,SSRM,FLNT,AFYA,HA,MMSI,FRGI,QRHC,AONE,CYTO,SLRX,ANAB,ITCI,ROVR,PTIX,FDBC,AXTI,ICHR,CVAC,CNCE,CSGP,NCBS,HRZN,FSTR,RDI,LAMR,ALZN,CYXT,CHX,VINO,ZUMZ,VECO,YSAC,ENG,ALPN,NEXT,ZNGA,PETS,SGMA,NILE,NTGR,URBN,HLTH,CARE,CVV,CREX,HNNA,SIVB,CLGN,AGIL,EEFT,CNFR,LYEL,SSPX,KARO,STRM,AWH,MANH,CIGI,MDRR,OTEX,GT,FOXA,SOTK,STTK,NTST,LANC,LRFC,XOS,FNWD",
        "EOSE,NSTG,MTEM,HLBZ,TAOP,LBTYB,FOX,HEC,ESPR,ORGN,MACE,COLM,DWAC,LPLA,PLMR,EDAP,XGN,LBTYA,HROW,JBSS,CNOB,BGRY,FORD,FENC,FKWL,CMCT,BLPH,IDAI,JOAN,CPZ,BYFC,STRL,EAR,OMCL,PRIM,ZKIN,NTWK,GAMB,MRVL,INMB,LIVE,PYR,GH,VIVO,CCSI,WOOF,TKNO,BANX,PRAA,EBIX,CMRX,ROLL,KNTE,CPRT,JACK,BHF,MLKN,MODV,OCDX,XRX,PCVX,FCAP,SYNA,SVRA,IDYA,TRMB,SBUX,CSSE,RCKY,FREE,AVAH,BCPC,CHEK,DAKT,ZIMV,OSW,SATS,SYPR,JRSH,PAYX,RGEN,CHW,MGTA,PCYG,KELYA,OPRT,RENO,STRN,HOTH,CAR,CHKP,GLMD,DBX,GRNQ,EGRX,ASLE,KNSL,CRON,SLGL,AGFS",
        "NCSM,CNXN,FB,SBAC,AGYS,GVP,SIGI,LSXMA,NYMT,SHEN,SHC,ERII,ADBE,AVCT,LSXMK,SBFM,IUSA,ALJJ,KDNY,MORN,AKYA,MGIC,POET,PLCE,SITM,FFIE,NGMS,MOBQ,CTG,UTSI,BZFD,SLDB,DSGX,DBTX,HLIO,MSEX,JVA,BBIG,CLFD,SOVO,ORGS,PXLW,GRMN,ICAD,CZWI,TTOO,MBIN,YTRA,VIR,FAST,KLTR,MYPS,QQQX,SVVC,MLAB,GOOG,XNCR,INVE,QRVO,CBAT,MASI,BNSO,CYAN,ICCC,CAMT,ADUS,EPRE,LKCO,SGC,ROIC,MXL,NTSX,PFIN,DGLY,HLNE,ROST,FRBK,DAIO,ERIE,PRFT,TSC,SIOX,THRY,GCMG,GOOGL,AVTX,LBTYK,HWKN,CGABL,CDNS,FEIM,ZSAN,FGI,ULBI,FULC,ENVI,ATEX,NXGN,PNFP,AZTA",
        "RYAN,NETL,PHIO,PAYA,LMAT,FSST,DCOM,RSSS,BLFY,HEES,PAX,GSIT,TRS,LMPX,FITB,PRDO,ANIK,CTHR,EXEL,TBLT,FRG,TBK,PFLT,AFRM,INPX,SGRP,MIDD,CTAS,NTRS,DJCO,WSBF,BBQ,SMPL,CWS,FHB,BCTX,ORCC,NGAC,CIVB,MRCY,TCRR,BWMN,CALB,MSTR,WETF,OCX,AVDR,FELE,NH,CVGI,FCRD,EMBC,BKR,CTRE,MEOH,ACIW,HIFS,PNTG,RPTX,ACCD,BLKB,UGCE,SOLR,STRA,EBTC,FREQ,RYTM,PRCT,CVLT,RVSB,BOTJ,PBPB,CCB,ENSG,AMAT,ESGR,CMCO,TWIN,ASO,IMMR,THRM,UCTT,VICR,YRIV,SPNS,JAZZ,AFIB,SLRC,HUGE,SASR,TMDI,LOPE,PDLB,OXBR,KELYB,EML,BRKR,AEI,NOBH,KTEC",
        "LCUT,JKHY,EMMS,RUTH,OPBK,CYTK,LNSR,CFB,SFST,MDCA,HBCP,PTEN,CHDN,BMEA,PLAY,KMPH,FCTR,LEGH,MDVL,TBLD,TRPL,UEIC,NGCA,TSAT,NXEOW,ACHC,SILC,INCR,RXST,PDCE,WSTL,STLD,CBRE,TITN,DLTH,RBB,QMAR,ADP,AMD,CNXC,MKTX,RTL,NMGC,PFC,TCCO,WSC,AGC,PECO,NTAP,DOOO,IART,AMRS,OCC,CSGS,ARCC,PLBC,BRQS,RESP,KTCC,PTVE,ELTK,NICK,RMNI,ACXP,LFVN,BIIB,BV,GFS,OFED,ADSK,LSCC,AXAS,SAL,HCCI,HFBL,UNAM,EXLS,VRA,DICE,WSFS,BMRN,IMAC,INDT,IVDA,CIZN,MVBF,RMBI,HCKT,HLMN,QIPT,COFS,UDMY,TAYD,PDCO,KXIN,SPOK,UBOH,AZYO,GLDB,LNT",
        "USLM,RDCM,ALRM,ABST,PPBI,SELF,GLNG,HGBL,EGBN,AIRT,PAHC,SNT,TA,STX,CSTE,CHEKZ,TRIP,NBAC,INCY,PSMT,MTEX,APOG,PHVS,DCPH,TRNS,VG,PRAX,LOCO,CERS,IBCP,NUVA,NLOK,USAP,MRAI,HURC,TRMK,DAVE,BKYI,SEIC,J,OCCI,AVIR,TFSL,NOVT,NEWP,AINV,CINF,PEBO,CLIR,EWCZ,SNOA,ATRO,CALM,NSTS,SWBI,AWRE,PNNT,RNST,MREO,CHUY,POOL,HALL,DSWL,GLPI,APPN,CSSEN,AVNW,GROW,NWFL,CSCO,ALKS,FUND,FISV,ARBKL,VBTX,HSON,ABVC,MMYT,HIBB,OAS,HOLI,ZEST,INBK,ITI,KZR,EWBC,HOMB,CVET,INTG,BJRI,CATY,STCN,BSET,CBAN,AURA,AFCG,FISI,BSRR,OFSSH,CLST",
        "SEMI,HOPE,CAKE,DLHC,REG,SBGI,SCPL,OSS,RPRX,NVMI,TBNK,MBWM,REFI,SWVL,CRMT,LAZY,FMBN,UHAL,GIGM,JAVA,BATRK,CLBK,OESX,GSM,PYPD,SIRI,ODP,HOFT,CBRL,VIGL,HTBI,IGAP,TBPH,COIN,RZLT,HBAN,RMBS,GAINZ,GTLS,EBC,OBNK,WDFC,INTC,MMMB,FORR,CSBR,HCSG,CMLF,UMPQ,CNAF,RILYZ,UBCP,FATBB,WFCF,ROCK,OBCI,FUNC,QCRH,MGI,HBNC,CASS,HTLF,BUSE,DOX,PIXY,PFG,GAIA,OXLC,FFBC,IRWD,WCFB,POAI,CBOE,MU,AHCO,UPC,WHF,ESLT,LIVX,SKYW,FFWM,FAT,LSXMB,UNB,AMRH,THCA,FSBC,SBRA,SRTS,ULTA,BATRA,PROV,CUBA,CFBK,ITRI,TCFC,CULL,FBNC,HALO,PSEC",
        "TROO,DEEP,ALGM,HBT,ZYXI,VIST,SAFT,WMPN,RGCO,STRT,INGP,YORW,BCTF,RMCF,SBT,COMS,CASA,GFAI,NXTD,TDSC,SNCY,LCNB,DNUT,BKCC,SYTA,OFS,PAGP,COLB,ACLS,APA,TCBC,NVEC,SBTX,ESSA,EMCF,SKYX,CAC,KRT,ARCW,TER,PROC,VCTR,NDSN,GAIN,HSIC,OBSV,TCBS,RMRM,BCOW,LBPH,CVCO,GENC,MOFG,DFH,UCBI,WULF,BOKF,CFFN,NATH,JUPW,HWC,CTRM,WSBC,LRCX,CEVA,KLAC,VLY,WTFC,AATC,LVTX,AUBN,RILYT,AAL,CHK,FULT,SCHL,MSVB,KEQU,ENTG,SLGN,TPG,PGC,GRVI,UBFO,PTGX,VTRU,KSCP,IVAC,NXST,DLTR,ALNA,IPGP,HROWL,MKSI,FFIN,EBMT,FRAF,TATT,MRCC,CPSI",
        "PEBK,RAND,TORM,FANG,CNSL,ISNS,CWCO,CFSB,STRS,NMFC,CMII,SPFI,TMUS,PRTS,CEG,WHLR,ACNB,BCOV,MSBI,RGP,CELH,METC,GECC,BUFF,OCSL,NGA,NAVI,GLBS,SFBS,USCB,ARKR,MYRG,LARK,OZK,LMST,GBCI,ROCC,SMTC,VLGEA,AFBI,HAFC,NFBK,INFO,LJPC,TXRH,UMBF,NTIC,SLM,NWLI,PMCB,CBSH,PMD,PFXNZ,NAKD,BDSX,PBHC,OPCH,REYN,THRN,PRMW,TCBI,GREEL,CCAP,FMNB,EIGR,GABC,MFIN,MATW,LBAI,EDTK,CRAI,SPTN,XPER,ATLCL,VWTR,NMIH,ACGL,SGH,ASUR,DELL,ATCO,MCBS,PTMN,FSBW,SCVL,RBKB,CVRX,VRNT,TURN,OXSQG,BELFA,CMPO,PATI,CRWS,III,VIAV,NWBI,PCB,IGLD,MTSI",
        "CDW,CSWI,CNNB,LSEA,BKNG,BJDX,WTBA,CLAR,MMLP,BFIN,TOWN,TCPC,FOSLL,ALGT,AMAX,ARTNA,OP,SNCRL,PCTI,AGRX,MITSY,RENT,GNRS,SBFG,ESEA,GIPR,MEIP,SOUN,EMBK,CSPI,SMBC,AMGN,SHOO,HMNF,ARIS,RMR,ATHN,METX,HSTM,OXLCZ,SFNC,DHIL,MANT,HOLX,PWOD,CHNG,FATBW,GRNA,ELSE,FCCO,JAKK,PCXCU,BPOP,PETV,MNTK,WINA,AAON,WASH,AVTR,UPST,ESCA,FUSB,RILYG,KRNY,CFVI,VALU,FNHC,ATCOL,LOAN,TXN,CASY,NSIT,AUB,NKSH,PBBK,VJET,BKSC,BRKL,SSB,GERN,WNEB,MEKA,VMAC,CLVS,AMAO,INOD,SSBI,FLEX,TMDX,NRIM,RWAY,CDX,UTHR,FLIC,RSTN,WHLRL,RICK,FRST,BLUW,FSFG",
        "SSSS,CSX,BMRC,LAXXU,VMD,COWNL,KTRA,MGYR,ATNI,PBIP,MACQ,OXSQZ,KFFB,UTAAU,EUSG,CENT,SFBC,BSGM,AMTB,AMNB,VTRS,PFX,MNRO,JSPRW,IBEX,HWCPZ,OXSQ,SMIT,BMAQU,OVLY,EFSC,SBCF,BFST,TVTY,VREX,CENTA,AZPN,VTSI,AUID,FFNW,ATOM,ACHN,FCUV,HVBC,WILC,MNDT,CBTX,MULN,VABK,GASS,IPWR,DRVN,ESOA,OSIS,ARIZU,LKFN,HNNAZ,SMID,VRRM,MAYS,WBA,JWEL,MPWR,FFBW,TSEM,AMBC,CGBD,LSBK,AVGO,ECPG,DALN,FDUS,QCOM,MGRC,GLAD,FBMS,AMKR,ISSC,VBFC,OTRA,FXNC,MBND,HELE,GILD,LGIH,GPRE,IBOC,GBDC,EVOP,LAUR,ABTX,MGEE,SSBK,ATLO,GCOR,INDB,SIFI,SMBK,OPOF,ATVI",
        "KLIC,NWE,LHCG,WLFC,EVOL,MCHP,SUMR,METCL,RDVT,ETTX,OSBC,ADI,NINE,WAFD,GHIX,GAINN,FMBH,OPHC,IDCC,NECB,BWB,GBLI,CFFSU,NWL,AGNC,UTMD,POLY,SAMG,ABIO,WABC,BWCAU,EA,DGII,ESGRO,FCNCA,AEIS,PBFS,UTAA,PCSB,NNBR,FRPH,NPABU,MCHX,ONYXU,INM,GEEXU,LMACA,CCRD,SLCRU,RBCAA,KFRC,CAPS,UFPI,DNAA,EVFM,MLHR,EXC,BCSAU,GLLIU,FIBK,AIRTP,GLBZ,ONB,ROCAU,TRTL,CSWC,ACEV,ZIONL,DSEY,ACAXU,KYCHU,NOVVU,GO,FLMN,PEP,NEWTZ,ISAA,LIONU,FRBNU,DAOOU,POWI,CSTR,ON,OXSQL,BREZ,BCML,MPB,GTACU,PTRS,BANR,CTXS,FVE,PFTA,HWBK,GHIXU,PEGRU,RBBN,ZINGU,CPAAU,ROCLU",
        "UONEK,FIACU,JSPR,GIFI,HAACU,NFE,NEWTL,RILYO,INTZ,CDK,NEWT,SCRMU,CPARU,TWNK,CLRCU,INTEU,LIVBU,UPTDU,QUIK,SAFM,STGW,TETEU,PLAB,FSEA,IQMDU,CBMB,EZPW,SWIR,HCMAU,UFCS,LUXAU,GNCA,AEP,JUGG,FTCV,OPINL,LGTOU,ENTFU,AFACU,ALSAU,PCH,AMCIU,CCMP,MRBK,VAXX,BPRN,LGVCU,RNDB,EMLD,BLTS,RILYN,CFFS,PWUPU,TGVCU,CAAS,GECCO,WVFC,BOCNU,FFDF,MLAIU,JBHT,ACAX,EOLS,PEGR,VTIQ,RWOD,ADEX,BRPM,JGGC,CITE,EVGRU,CNGLU,PCCTU,ENCPU,LIBYU,SBSI,CPAR,FIZZ,BHSE,OCAX,IIN,FRME,XEL,CPAA,BRIV,HCNE,UVSP,GTPB,THCP,ASPC,ALOR,FGMCU,FNVTU,CDZI,SMAPU,GVCIU,REVE,TOACU,MCAAU,ICCH",
        "DALS,RVACU,EPAY,BSBK,LCA,KDP,ITRN,GSRMU,AHPA,FEXDU,AMWD,GLEEU,PAFO,SCRM,SHBI,ANAC,HWELU,ICPT,NHIC,FINM,SAMA,GHACU,CHWA,BLSA,EMLDU,IVCPU,FGMC,IMKTA,AFARU,WTMAU,BRACU,SCMAU,IOACU,THACU,XPDBU,NLIT,RIBT,ITHX,STBA,SPCM,FOUN,KIII,OTTW,MCAE,BWC,ARYE,DNAD,ITAQU,ZT,KVSC,TCVA,GAMC,ACQR,PLMI,PSAG,TETC,TIOA,FTAA,MSDA,GSEV,MON,MSAC,NVSA,SPKB,KRNL,LEGA,HCIC,KLAQ,SCOB,CLIN,SHQA,COOL,NOAC,HMPT,LUXA,PEPL,RCACU,EJFA,BTWN,VCXA,MCAF,ACTD,IMPX,SGHL,DRAY,GSAQ,NPAB,CONXU,BIOSU,GTAC,PWUP,DHAC,SHCAU,VMCA,BWAQU,CHEAU,TGAN,LVACU,TSBK,MITA",
        "GPAC,JCIC,JCS,AVO,DNAB,JYAC,LSPR,WAVC,PANA,ROSS,FRSG,NDAC,SMIH,DTOC,REVH,ACAH,FRON,GHAC,GTPA,HERA,TWLV,AGGR,DHCA,OEPW,SLAM,SPTK,SVFB,LGAC,RMGC,TBCP,MTAC,TZPS,VII,CFIV,IIII,OHAA,PTIC,ANZU,SCOA,HAAC,MCAG,PAQC,CONX,GSRM,BMAQ,AKIC,SRSA,DAOO,GIIX,RVAC,ASPA,TGAA,SIERU,ENTF,LJAQ,SKYAU,AIMAU,ONYX,PRLHU,DPCSU,BRKHU,MPRAU,MUDS,RFACU,CNTQ,FOXW,GLEE,ALORU,SPCMU,RACYU,JGGCU,AHPAU,TRST,GRCY,CRUS,ASAX,FLDR,VLAT,KVSA,ANAT,ETACU,ZING,NMMC,ACAB,RCHG,OLITU,EDNC,GLDD,XFINU,YOTAU,SSSSL,CSLMU,HCVI,SLVR,CDAQ,ALPA,LITT,SKYA,AFAQ,KSI",
        "FMIV,FRW,NSTC,DNAC,ARRW,COLI,TBSA,JOFF,SSAA,TSIB,ZWRK,ABGI,ARYD,ITQ,PFDR,SVFA,FTVI,HCAR,OSTR,BSKY,DLCA,PRSR,SCLE,ARBG,BNNR,PHIC,RFAC,MONCU,AVAN,IGAC,SIER,INTE,FHLT,IMXI,WAVS,FXCO,ETAC,HAIA,SMAP,ROCG,FNVT,APSG,VHNA,FTII,MTRY,SHUA,APXI,ENCP,PPYAU,GACQ,ARCK,CLAQ,LATGU,MEOA,NCACU,RWODU,CFFE,TLGYU,BHSEU,MPAC,BENE,ARGU,ISLE,LNTH,CITZ,DHBC,GOBI,LHAA,NRAC,FVAM,CIIG,TMKR,GECCM,MURF,ESACU,TOAC,FTIIU,ASRV,GPCO,IBTX,GGAA,SGHLU,AABA,AACOU,ABDC,ABIL,ACBA,ACBAU,ACBI,ACIA,ACTT,ACXM,ADAL,ADER,ADMS,AEAC,AEGN,AFH,AHRNU,AIMT",
        "AIPT,AKCA,AKRX,ALAC,ALDR,ALGR,ALQA,ALRS,ALSK,ALTA,ALXN,AMAG,AMRB,AMTBB,ANCX,APAC,APEX,APHA,APIC,APR,APXTU,ARCI,AREX,ARNA,ARQL,ARRS,ARTE,ARTX,ARYAW,ARYB,ASCL,ASCMA,ASFI,ASNA,ASNS,ASTIW,ASV,ATIS,ATSPT,ATTU,ATVC,AUTH,AVAC,AVHI,AWSM,BASI,BBOX,BBRY,BCAC,BCDS,BCOM,BDSI,BEER,BFYT,BHBK,BIQI,BLMT,BMCH,BMTC,BNCL,BOCH,BOCN,BOJA,BOKFL,BOLD,BOWX,BPFH,BPYU,BREW,BSTC,BTAQ,BTNB,BVSN,CADC,CAHC,CALI,CARB,CARO,CART,CASM,CATM,CATS,CBLK,CBMG,CBPO,CCGM,CCNI,CCRC,CELG,CENH,CETV,CFFA,CFFAW,CGRO,CHMA,CHPM,CHUX,CIFS,CIIC,CLAS",
        "CLCT,CLDB,CLDC,CLIRW,CLRM,CLRS,CLUB,CMFNL,CMLT,CMTA,CNAT,CNBKA,CNIC,CNST,CONE,CORE,CORV,COVA,COWNZ,CPAH,CPAQU,CPTI,CRAY,CREE,CRZO,CSFL,CSOD,CSWCL,CTBK,CTRC,CTRL,CTRV,CTWS,CUR,CVAS,CXDC,CY,CZFC,DBCP,DCAR,DCRBU,DCRN,DDMX,DDMXU,DEAC,DEACU,DEER,DEST,DFBH,DFRG,DGNS,DHHC,DHXM,DIET,DISCB,DISCK,DLBS,DMAQU,DMPI,DNBF,DNKN,DOVA,DRAX,DRCO,DRMT,DRNA,DRYS,DSPG,DTUL,DTUS,DTYL,DTYS,EAGL,EAGLW,EASI,EBSB,ECHO,ECOL,EDCI,EEI,EENC,EFII,EGOV,EHR,EIDX,EIGI,ELGX,EMCI,ENFC,ENT,ENVIU,EPHY,ERES,ERI,ESIO,ESND,ESTR,ESXB,ETFC,EUCR",
        "EVLVU,EVOJ,EVSI,EXFO,FABK,FACT,FBNK,FBSS,FCACU,FCBP,FCCY,FCSC,FDUSG,FDUSL,FDUSZ,FHC,FLAC,FLAT,FLIR,FLLC,FLXN,FMBI,FNJN,FNSR,FOGO,FOMX,FOREU,FORK,FPRX,FRAN,FRED,FRTA,FSAC,FSACW,FSCT,FSRX,FTAC,FTD,FTOC,FTPA,FTR,FTSV,FWAA,FXCOU,GARS,GBLIL,GBLIZ,GCAC,GDEV,GECCL,GEEX,GENQU,GFED,GFGD,GFN,GFNSL,GFNSZ,GGMC,GHDX,GHIV,GHIVU,GIAC,GIG,GIW,GLADL,GLIBA,GLUU,GMBT,GNMK,GNMX,GNOG,GPAQ,GPIC,GRSV,GRSVU,GSKY,GWACU,GWGH,GWII,GXII,HABT,HAIR,HBK,HBMD,HBP,HCAP,HCAPZ,HCCH,HCII,HDS,HEAT,HFBC,HHHHU,HHT,HIII,HMCO,HMHC,HMSY,HMTA,HORI",
        "HPJ,HPT,HQCL,HSAC,HSAQ,HWCC,HWCPL,HYGS,IBKC,ICBK,ICON,IDSA,IDSY,IDTI,IEC,IGLDF,IGNY,IGTA,ILG,IMAQ,IMDZ,IMED,IMI,IMMU,IMVTU,INAP,INBKL,INKA,INOV,INSY,INWK,IOAC,IOTS,IPAS,IPHI,IPHS,IQMD,ISBC,ISCA,ISRL,ITAC,ITAQ,JASN,JASNW,JMPNZ,JUNS,JWACU,KACL,KANG,KCAPL,KDMN,KEYW,KGJI,KIN,KLDO,KOOL,KOR,KPFS,KSMTU,KURI,KVSB,LABL,LATN,LCAP,LEGO,LEVL,LEXEA,LEXEB,LFTR,LGCY,LGST,LGSTU,LION,LMNX,LOAC,LOGM,LORL,LOXO,LSAC,LTXB,LVGO,MAAC,MACU,MACUU,MAMS,MB,MBFI,MBTC,MBTF,MCACU,MCFE,MDCO,MDH,MDSO,MEET,MELR,MFINL,MFNC,MFRM,MFSF",
        "MGLN,MIK,MINI,MIRO,MJCO,MLAI,MLAN,MLNT,MLNX,MLVF,MMAC,MMDM,MNGA,MNTA,MNTX,MOBL,MPVD,MRIC,MRLN,MSBF,MSON,MTEC,MTECW,MTLK,MTSC,MXCT,MXIM,MXWL,MYL,MYOK,MYOS,NANO,NAVG,NBL,NBST,NCOM,NEBU,NEOS,NEWA,NEWTI,NFIN,NGHC,NGHCZ,NHLD,NIHD,NITE,NMCI,NMFCL,NOEC,NOVS,NPTH,NTGN,NTII,NTRI,NTRP,NUAN,NUBIU,NUCO,NVACU,NVLN,NVMM,NVOS,NVTR,NXEO,NXTM,NYNY,NYXH,OBAS,OCSI,OCSLL,ODDJ,ODT,OFSSG,OFSSI,OFSSL,OFSSZ,OGAR,OHAI,OHPA,OHRP,OLBK,OLIT,OMED,OMP,ONCE,ONSM,OPB,OPESU,OPINI,ORBC,ORBK,ORIT,ORPN,ORSN,OSIR,OTEL,OTIV,OXFD,OXUS,PAAC",
        "PACQ,PAE,PAND,PARD,PBBI,PBCT,PCCT,PCMI,PDLI,PEDH,PEGI,PETX,PFBI,PFPT,PFXNL,PGLC,PGNX,PGRX,PHCC,PLTEU,PMBC,PNNTG,PNTR,PPD,PRAH,PRCP,PRGX,PRNB,PRTG,PRVL,PS,PSDO,PSYS,PTLA,PTOC,PTVCA,PTVCB,PUB,PXMD,PYDS,QADA,QADB,QELL,QTNA,QTRH,RAM,RARX,RAVN,RBNC,RBZ,RCLF,REPR,RESN,RHDM,RILYH,RILYI,RILYM,RIVE,RNET,ROC,ROCR,ROSE,RP,RTRX,RTTR,RTWI,RUBI,RVEN,RVLT,SAEX,SAII,SANB,SAUC,SBBP,SBBX,SBEA,SBLKZ,SCAC,SCACW,SCAQ,SCMA,SCR,SDAC,SFLY,SGIC,SGYP,SHAC,SHLO,SHOS,SHSP,SIC,SINA,SITO,SKIS,SLCR,SLCT,SMSA,SMTK,SMTX,SNDE",
        "SNH,SNNA,SNRH,SOLY,SONG,SORL,SPEL,SPHS,SPRT,SQBG,SSFN,STAY,STB,STFC,STFR,STLRU,STML,STMP,STND,STNL,STPP,STWO,STXB,SUNS,SV,SVA,SVBI,SVOK,SYKE,SYNC,TACO,TBIO,TCBIL,TCBIW,TCF,TCLD,TECD,TERP,TFCF,TFCFA,TFM,THBR,THOR,TIBR,TISA,TIVO,TLF,TLGT,TLGY,TLMD,TMCX,TMPM,TMTS,TNAV,TNT,TOTA,TPCO,TPNL,TRCB,TRIL,TRIT,TRMT,TROV,TSG,TSRO,TST,TTCFW,TTPH,TTS,TUES,TULY,TWCT,TYPE,UBNK,UBNT,UCFC,ULTI,UPL,UROV,USCR,VACQ,VAQC,VCVC,VEAC,VEACW,VIAB,VIE,VIH,VINCW,VISN,VLRX,VMACU,VMCAU,VMET,VOSO,VPCB,VRML,VRTU,VVUS,WALD",
        "WEBK,WHFBZ,WHLRW,WIFI,WINS,WMGI,WMGIZ,WTMA,XLNX,XLRN,XOG,XON,XONE,XPDI,YGTY,YNDX,YOGA,ZAGG,ZGNX,ZGYH,ZIXI,ZN,ZNTE,MAAQ,HFWA,GLLI,EDTX,VHNAU,APXIU,KINZ,PONO,ALSA,ATAK,BLNG,HLAH,DGNU,OTTR,IFIN,UNTY,DSAC,BRLI,GLAQ,ACKIT,IPVI,TEKK,LMAO,MURFU,PACX,GLSPT,ATAKU,BSGA,CRECU,FRLA,VMGAU,CENQ,DECAU,GVCI,JMAC,MSSAU,NOVV,USCT,BPACU,PBAX,TGAAU,VSAC,AFAC,CNGL,IVCB,SWAG,SZZL,SHCA,ALTU,FEXD,DMAQ,DUNE,FIAC,DUETU,EVGR,LGVC,CLAY,BPAC,LBBB,VMGA,CBRG,GDNR,TGVC,BRKH,GMFI,BWAQ,LEAP,ASCA,DUET,TETE,FATP,GATE,SWSS,AACI,LAX,PGRW,BHAC",
        "CTAQ,KAIR,AURC,DILA,POW,PMGM,GNAC,SWET,FSSI,KAII,PUCK,TRCA,LDHA,KYCH,TWCB,TPBA,FICV,VELO,JAQC,ICFI,IGIC,CARV,FRBA,MAQC,VTAQ,TRON,JWAC,CCTS,ARIZ,MLAC,RICO,CITEU,ARCKU,OTEC,VSACU,DTRT,OHAAU,LIBY,OXAC,NCAC,RNER,UPTD,CMCA,LFAC,RACY,LIVB,MPRA,XFIN,NHICU,WINV,GENQ,LGTO,WWACU,DCRD,BRAC,VBOC,GDST,ENER,EAC,MACA,OMEG,XPDB,INAQ,BYTS,CRZN,EBAC,RACB,RXRA,CLAQU,APTM,IPAX,AIBBU,MIME,AEHA,SYNL,AEAEU,PCX,CZNC,CPTAL,LVRA,SZZLU,MRCCL,NHTC,SVFC,MAAQU,VCKA,USCTU,SVNAU,CLOE,FRLAU,MCAA,GBRG,LFACU,ENERU,ESAC,PPHP,LATG,CPAQ,AOGO,AEAE",
        "CREC,SVNA,AIB,BIOS,MEAC,GLBL,CSLM,CCAI,FWAC,HPLT,HWEL,APMI,VIRC,GGAAU,FRBN,GCTK,BCSA,BNIX,DKDCA,IVCBU,WAVSU,GMFIU,HHGC,SAGA,TCAC,WWAC,DPCS,DYNS,IVCP,IXAQ,LCAA,GLHA,LFLY,PCAR,SPK,IIVI,ADTN,BFC,AOGOU,SHUAU,PINC,CCTSU,SGIIU,PRLH,SGII,CWBC,NVAC,RCAC,GBNY,SEVN,PROS,NAAC,VENA,CBRGU,GGGV,PLAOU,LSPRU,COMM,LVAC,LAAA,ORIA,OCFC,REGI,TIVC,PRSP,ESBK,RRBI,DSACU,GDNRU,CLINU,GDSTU,ASCAU,ACABU,PPYA,ADOC,UBSI,LEND,FCFS,CFFI,PDEX,PVBC,VECT,IGTAU,MCAGU,HYAC,DIOD,VSEC,XPAX,BBSI,HAIAU,THAC,BIOT,DISA,BLMN,COHR,CERN,CMCAU,HORIU,HCMA,AHRN",
        "VBOCU,ROCL,BOMN,VIA,PBNC,BDGE,MCFT,HTBK,SAGAU,GFGDU,SENEA,ADALU,GPOR,MGPI,JCTCF,SGA,AGBA,FBSI,SP,GECCN,PLPC,GNTY,EFBI,DORM,COHU,CHMG,JFBC,AMCI,RGLS,CBFV,PFHD,VC,MCBC,GNTX,HCOM,KACLU,ASPAU,SRCE,LACQ,FVCB,LBC,CNFRL,HON,DFVL,HONE,CBNK,MYFW,PTC,MODD,XENT,USEG,SAIA,FNLC,CACC,LBBBU,BWAC,AROW,OMQS,NBTB,CCNE,UAL,NSEC,PPHI,SNEX,SSTI,FCBC,PDFS,XPEL,DVCR,WEYS,HHS,KE,LINK,ARTA,AMSF,IROQ,WORK,SLAB,BANF,RCII,GSBC,CVLY,CIBN,SPRO,LITE,CCEP,NODK,ACTG,TESS,ABCB,DMAC,COKE,CYBE,RBCN,MAR,CTBI,SHIP,MOTN,INBKZ,ATSG",
        "TTMI,DHACU,PRGS,DYSL,TCBX,CVBF,GEOS,OBT,NXPI,ARTAU,ESSC,MBII,MNST,SANM,CFBI,MDLZ,MBCN,TPTX,AFHBL,PESI,COOP,FFIC,USAT,SYBT,INVZ,BLDR,JRVR,RGTI,GYRO,GDYN,NBN,CTRA,RNWK,MERC,HLIT,CATC,EQBK,BWFG,OVBC,AAWW,TGA,SENEB,BSVN,FLXS,ZVO,ONEW,ODFL,STBK,KINS,DZSI,TILE,LECO,BECN,DSKE,BIOX,PFSW,EYEG,THFF,PFIS,CHRW,PKBK,HAS,ISTR,FORM,TXMD,DXPE,RGC,DHCNL,FNKO,CCBG,MRTI,BROG,PLXS,PPC,ARPO,CINC,ESQ,PFIE,COWN,NTCT,FWRG,CHEF,BELFB,RELL,KNTK,VERY,QBAK,WSTG,AMCR,ACT,PTI,GRBK,DFVS,MNSB,GCBC,PXS,RELV,NYMX,GRIN,MBUU",
        "RUSHA,SWKH,CHCO,RADI,RUSHB,ALCO,HTLD,DBGI,BCBP,LKQ,LSTR,KALU,LFUS,UFPT,KBAL,SMMF,SCON,BTBD,PNRG,GMTX,TZOO,TH,THTX,FBIZ,HST,INSEW,VTYX,HURN,AIMC,MHLD,INSE,PAVM,SCSC,ORRF,MICT,ASTE,NBSTW,FWRD,VRRMW,JMSB,BSPE,MRAC,AHAC,IOSP,INVZW,TCBK,USAK,SIGA,ARCB,DFPH,TCRT,GNSS,DXR,PATK,EPSN,FMAO,ARYA,ELEV,CVLG,ENJY,WRTC,PLYA,EGLE,EXPD,GLRE,COCO,PANL,HOWL,PRSC,MRTN,BAOS,LVLU,PKOH,EDRY,WERN,NDLS,PACE,AMAL,IMRA,IIIN,ADOM,BTB,DGICA,MAT,HNRG,BTTX,CECE,AKAN,YGYI,HCDI,OSMT,PTSI,TAIT,RLYB,SCTY,SBLK,ANNX,WIRE,THER,NWPX",
        "VSPR,AXGN,SNBP,WDC,DGICB,ANIX,HUBG,HOUR,AMST,LYTS,GOGL,BRID,TAPR,FGBI,SKYE,PMTS,CPSS,AMR,OST,HOL,SREV,NKTX,EYES,AVT,TRMD,UONE,CMPX,ANTX,VTNR,ULH,HCCC,HUDI,NTUS,ACTC,NSYS,SRNG,POWL,HPK,RCMT,AIRG,SMCI,TIG,HDSN,SRRA,PVAC,PPIH,PCOM,CMLS,CPHC,ATRS,PME,MKTY,AMHC,SCPE,LONE,BON,TNON,HMTV,NVCT,RDBX,NETE,LWAC,GTYH,CLEU,TRCH,TRNX,CVLB,CYN,CMPI,IAIC,APLD,CRGE"
    ];

    var collectedData = [];
    var endData;
    var qsParams = new URLSearchParams(window.location.search);
    console.log(Number(qsParams.get("groups")));

    if ([NaN, 0].includes(Number(qsParams.get("groups")))) {
        endData = data.length;
    }
    else {
        endData = Number(qsParams.get("groups"));
    }

    for (var i = 0; i < endData; i++) {
        console.log(`Retrieving data for group ${i + 1} of ${endData}...`);
        var symbols = data[i];
        let timeoutEnd = (new Date()).getTime() + 12;
        do {} while ((new Date()).getTime() < timeoutEnd)
        let url = `https://cloud.iexapis.com/stable/stock/market/batch?symbols=${symbols}&types=stats&token=${apiKey}`;
        const done = await axios.get(url)
            .then(response => {
                let keys = Object.keys(response.data);
                keys.forEach(key => {
                    try {
                        let chartData = response.data[key].stats;
                        collectedData.push({
                            ticker: key,
                            day30: chartData.day30ChangePercent,
                            day5: chartData.day5ChangePercent,
                            marketcap: chartData.marketcap
                        });
                    }
                    catch {
                        return;
                    }
                });
            })
            .catch(error => {
                console.log(error);
            });
    }

    console.log(collectedData);

    collectedData.sort((a, b) => {
        if (Math.abs(a.day30 + 0.3625) < Math.abs(b.day30 + 0.3625)) {return -1;}
        else if (Math.abs(a.day30 + 0.3625) > Math.abs(b.day30 + 0.3625)) {return 1;}
        else if (a.ticker > b.ticker) {return 1;}
        else {return -1;}
    });

    drawTable(collectedData);
})();